// <auto-generated />
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Tokito.Data;

#nullable disable

namespace Tokito.Migrations
{
    [DbContext(typeof(GameStore))]
    [Migration("20260422164000_AddRegionalPriceMetadata")]
    partial class AddRegionalPriceMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            var snapshot = new GameStoreModelSnapshot();
            var buildModel = typeof(GameStoreModelSnapshot).GetMethod(
                "BuildModel",
                BindingFlags.Instance | BindingFlags.NonPublic);

            buildModel!.Invoke(snapshot, [modelBuilder]);
#pragma warning restore 612, 618
        }
    }
}
